### ISSUE TITLE
[ENHANCEMENT] Add releases to AUR / Chocolatey

### ISSUE THREAD

**Issue by Mayurifag** [slok/agebox#113]
I wish to say thanks a lot to maintainers for a very promising project, that solves a very common problem via something easy-to-understand non-complex concepts, I enjoyed a lot to work with it after I understood some of the projects ideas.

However, I wish agebox to be presented in package managers of systems I use and I feel kinda lazy to download binary from releases page and find where could I put it on my $PATH folders. I guess, that would be the first huge step for project to become mature, to be used by huge amount of people (developers). 

Thanks in advance, sorry for my english.

**Comment by slok** [comment]
Hi @Mayurifag!

Thanks for the kind words :smile: 

You are right, we should have an easier way of distributing Agebox. Sadly I don't have time to maintain an Arch package (I am an Arch user myself), and I don't have Windows.

However, I was thinking for some time about creating an [asdf](https://asdf-vm.com/) package. Would this solve your problem?

**Comment by Mayurifag** [comment]
Yea, asdf plugin seems very promising, although I don't get the problem you will solve via asdf. 

We need asdf when our projects depend on several version of node/ruby/etc., but agebox seems not to be that tool, which may break backward compatibility in future (or I'm hoping so 😄 ).

Furthermore, asdf is not supported in Windows — thats the point which makes me to think that asdf solution is not the thing I would like to contribute into, my apologies. And chocolatey support is the thing project needs, because there are many plugin users (including me) thay may time in time code or hotfix in windows development something small, but needed to be encrypted, — so, users may use chocolatey to fast-install the plugin into system, use choco for fresh-installed-windows administration, etc.

**Comment by slok** [comment]
>Yea, asdf plugin seems very promising, although I don't get the problem you will solve via asdf.
>
>We need asdf when our projects depend on several version of node/ruby/etc., but agebox seems not to be that tool, which >may break backward compatibility in future (or I'm hoping so smile ).

Well, asdf solves 2 different problems, multiple versions and easy and simple app distribution in any GNU/Linux distro and MacOS. So in the case of agebox, is a generic way of installing it in *nix systems.

> I would think about AUR/choco maintaining myself, if no volunteers would be presented. 🙆🏻‍♂️

Awesome! thanks.

In other news, I already created [agebox asdf plugin](https://github.com/slok/asdf-agebox) and submitted a [PR](https://github.com/asdf-vm/asdf-plugins/pull/526) on the official plugin list.

**Comment by 4x0v7** [comment]
Hey everyone! Just wanted to chime in here. I have created a bucket for [scoop](https://scoop.sh) and a manifest to install agebox.

If you're on Windows and haven't used `scoop` before I would encourage you to check it out 😃 

The TLDR is;

```shell
scoop bucket add kubetools https://github.com/4x0v7/kube-scoop
scoop install agebox
agebox --version
```

Scoop makes it simple to switch versions:

```shell
scoop install agebox@0.6.0
scoop reset agebox@0.6.0
agebox --version
v0.6.0
scoop update agebox
agebox --version
v0.6.1
```

That repo is automatically updated as new versions are released.

**Comment by slok** [comment]
Thank you @4x0v7! I'm sure that this will be helpful for Windows users :)

**Comment by Mayurifag** [comment]
Oh and I've just noticed there is no homebrew package available 😭

**Comment by nathanEmity** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @andantonyan, @ossdate, @Wylie-S, @randomgenerator2019, @Mel-NLY, @jiaoyk, @pureTrue

**Comment by wezm** [comment]
Just dropping in to mention that I created an AUR package for agebox:

https://aur.archlinux.org/packages/agebox

**Comment by slok** [comment]
Hey @wezm Many thanks!
