### ISSUE TITLE
[feature] allow users to communicate private key passphases more securely

### ISSUE THREAD

**Issue by jpluscplusm** [slok/agebox#143]
This Issue was originally going to be "please allow private-key operations to be delegated to an ssh-agent", but having read the ssh-agent protocol, it appears that that isn't possible. The only private key operation available is signing something, not encrypting it.

The root cause of the above request was me trying to solve the problem that building a developer/ops workflow around agebox is currently more annoying and fiddly than it *could* be. This is because a script that does any repeated validation/etc of encrypted files (e.g. working out which files *need* to be re-encrypted, versus those that could be `git restore`d) will ask for the ssh passphrase on every `agebox` invocation.

To avoid this, I could use the `--passphrase=FOO` parameter. But this isn't a great solution, for a few reasons:

- it temporarily exposes the passphrase in the machine's process table, which might be a poor idea for shared/CI/etc machines
- it requires me/the-script to solve the quoting problem for every possible set of shell meta-characters that /might/ exist in a passphrase
- it leaves the passphrase in the shell's history file, if used interactively

Other tools have solved this problem in a couple of different ways:

- sigtool uses environment variable indirection: https://github.com/opencoff/sigtool/blob/master/sigtool.go#L98
  - NB this **isn't** simply `foo-tool --passphrase $ENVVAR`. It communicates the *name* of the envvar that the process should look up, independently, not the value: e.g. `foo-tool --passphrase-envvar-name ENVVAR`
- a variety of tools implement a flag that means "read STDIN and assume that a machine/script is talking to you, not a human, so don't output any prompts/etc"

Whilst the envvar-name-indirection route is probably the more useful one, I can see arguments for using STDIN from a security perspective. It'd be great to have either of these -- or both! -- as options for agebox :-)

**Comment by slok** [comment]
Hi @jpluscplusm!

Thanks for all the issues and for taking the time to explain them all!

This is a very nice Idea, I already implemented both (env and stdin). :smile:

**Comment by jpluscplusm** [comment]
Hey @slok - thank you so much! That's fab of you to put this in so quickly :-D

I've been using [my `asdf` plugin for versioning simple downloads](https://github.com/jpluscplusm/asdf-arbitrary-code-execution) to install agebox from the GH Releases you put out - feel free to ping me as & when & if you cut another release, and I'll bump [the version that's tested](https://github.com/jpluscplusm/asdf-arbitrary-code-execution/blob/main/dagger.cue#L100) :-)
