### ISSUE TITLE
Error if `~/.ssh` is a symlink

### ISSUE THREAD

**Issue by wezm** [slok/agebox#218]
On my system `~/.ssh` is a symlink:

```
.ssh ⇒ /home/wmoore/.dotfiles/private/ssh
```

`agebox` does not seem to like this. I think because [WalkDir does not follow symlinks](https://pkg.go.dev/path/filepath#WalkDir):

```
error: "decrypt" command failed: could not decrypt: could not get private key: could not read private key "/home/wmoore/.ssh" data from file: read /home/wmoore/.ssh: is a directory
```

It would be great if `agebox` followed symlinks when locating keys.

**Comment by slok** [comment]
Hey @wezm!

Indeed!

recursive walks following symlinks adds too many edge cases, so I'm not confortable opening pandora's bug box 😆, so as a middle ground solution between simplicity, reliability and practicality, I will add 1st level symlink follow, so, if the root path is a symlink (like the use case you have), it will make the discovery on the followed link and from that on, it will act as a regular directory walk.

**Comment by slok** [comment]
@wezm I have cut a new release: [V0.8.0](https://github.com/slok/agebox/releases/tag/v0.8.0). Whenever you can, please test it 🙏. 

Thanks!

**Comment by wezm** [comment]
Thank you for the quick fix @slok. One level of symlinks seems like a reasonable compromise. I can also confirm it works for me now:

```
INFO[0000] Loaded private keys                           keys=2 svc=storage.fs.KeyRepository version=dev
WARN[0000] SSH key passphrase required                   svc=key.age.Factory version=dev
INFO[0000] Enter passphrase for ssh key:                 svc=key.age.Factory version=dev
INFO[0011] Secret decrypted                              secret-id=secret/test svc=box.decrypt.Service version=dev
```

I've also updated the AUR package to 0.8.0.

**Comment by slok** [comment]
Awesome 👏  Thanks again @wezm!
