### ISSUE TITLE
What private key format does agebox expect?

### ISSUE THREAD

**Issue by cezarmathe** [slok/agebox#79]
I tried decrypting a file with the private key stored in the file generated by `age-keygen -o key.txt` and it just won't work.

age version: devel (package version: 1.0.0rc.1-2, Arch Linux)
agebox version: dev (installed with `go install github.com/slok/agebox/cmd/agebox@v0.5.0`)

**Comment by slok** [comment]
Hi @cezarmathe! thanks for the issue.

Agebox supports the same keys as Age:

- RSA
- Ed25519
- X25519

I just noticed that it fails when there is a comment or newlines in the age files, so I'll add a sanitization process to remove these bits in case they are present.

You can see a valid key here: https://github.com/slok/agebox/blob/main/tests/manual/keys-priv/key7

**Comment by cezarmathe** [comment]
I tried without the comments, too. I think the culprit in my case was the newline at the end of the file, added automatically by editorconfig.
